# POST http://localhost:3000/signup 
# Content-Type: application/json

# {
#     "fullname" : "john",
#     "email" : "john@gmail.com",
#     "password" : "John@123"
# }

#GET http://localhost:3000/get-upload-url

POST http://localhost:3000/create-blog
Content-Type: application/json

{
    "title": "test title"
}